package org.gitanimals.core.redis

object RedisPubSubChannel {

    const val USER_CONTRIBUTION_UPDATED = "USER_CONTRIBUTION_UPDATED"
    const val GUILD_CONTRIBUTION_UPDATED = "GUILD_CONTRIBUTION_UPDATED"

    const val SLACK_INTERACTED = "SLACK_INTERACTED"
    const val SLACK_REPLIED = "SLACK_REPLIED"

    const val DEAD_LETTER_OCCURRED = "DEAD_LETTER_OCCURRED"

    const val NEW_PET_DROP_RATE_DISTRIBUTION = "NEW_PET_DROP_RATE_DISTRIBUTION"
}
